config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'cars#index'

  resources :cars, only: [:index, :show, :new, :create, :update]

end

app/models/car.rb
class Car < ActiveRecord::Base

belongs_to :user

belongs_to :shape
belongs_to :colour
belongs_to :wheel_style

has_many :car_decals
has_many :decals, through: :car_decals

# before_validation :assign_car_to_current_user

protected

# def assign_car_to_current_user
# 	self.user = current_user
# end

end

app/models/car_decal.rb
class CarDecal < ActiveRecord::Base
	belongs_to :car
	belongs_to :decal
end

app/models/car_options.rb
class CarOptions

	def shape
		@shape ||= Shape.pluck(:name, :id)
	end

	def colour
		@colour ||= Colour.pluck(:name, :id)
	end

	def wheel_style
		@wheel_style ||= WheelStyle.pluck(:name, :id)
	end

end

app/models/colour.rb
class Colour < ActiveRecord::Base
	has_many :cars

end

app/models/decal.rb
class Decal < ActiveRecord::Base

	has_many :car_decals
	has_many :cars, through: :car_decals
end

app/models/shape.rb
class Shape < ActiveRecord::Base

	has_many :cars
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars

end

app/models/wheel_style.rb
class WheelStyle < ActiveRecord::Base
	has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :authenticate_user!

	def index
		@cars = Car.all
		respond_to do |format|
			format.html 
			format.json { render json: @cars}
		end
	end

	def new
		@car = Car.new
		@select_options = CarOptions.new
	end

	def show
		@car = Car.find(params[:id])
		respond_to do |format|
			format.json { render json: @car}
		end
	end

	def create
		@car = Car.new(car_params)
		@car.user = current_user
		if @car.save
			redirect_to(cars_url, notice: "new car '#{@car.name}' created")
		end
	end

	def update
			@car = Car.find(params[:id])
		respond_to do |format|
			if @car.update(car_params)
				format.json { render json: @car, status: :ok }
			end
		end
	end

	private

	def car_params
		params.require(:car).permit(:id, :name, :shape_id, :colour_id, :wheel_style_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
	
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :shape_id %>
		<%= f.select(:shape_id, options_for_select(@select_options.shape)) %>
	</div>

	<div class="field">
		<%= f.label :colour_id %>
		<%= f.select(:colour_id, options_for_select(@select_options.colour)) %>
	</div>

	<div class="field">
		<%= f.label :wheel_style_id %>
		<%= f.select(:wheel_style_id, options_for_select(@select_options.wheel_style)) %>
	</div>

	<div class="actions">
		<%= f.submit("Create New Car", class: "button expand") %>
	</div>


<% end %>

app/views/cars/index.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Listing Cars</h1>
		<ul class="large-block-grid-3 medium-block-grid-2 small-block-grid-1">
			<% @cars.each do |car| %>
				<li><h3><%= car.name %></h3>
					<p>user: <%= car.user.id %></p>
					<p><%= car.shape.name %></p>
					<p><%= car.colour.name %></p>
					<p><%= car.wheel_style.name %></p>
				</li>


			<% end %>
		</ul>
		<%= link_to "New Car", new_car_path %>
	</div>
</div>

app/views/cars/new.html.erb
<div class="row">
	<div class="large-4 large-offset-4 columns">
		<h1>New Car</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>